version: '3'

services:
  api:
    image: 'bookstore-api:latest'
    build:
      context: api/
    restart: always
    container_name: bookstore-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-db:5432/bookstore
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  ui:
    image: 'bookstore-ui:latest'
    container_name: bookstore-ui
    build:
      context: ui/
    restart: always
    stdin_open: true
    volumes:
      - ./ui:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: 'postgres:13.1-alpine'
    container_name: bookstore-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bookstore